* fix many bugs ,  master and slave stop service completely , fix client link
M    src/shell/client_install_func.sh
M    src/shell/client_remove
M    src/shell/crawlzilla
M    src/shell/client_install
M    src/shell/master_remove

diff --git a/src/shell/client_remove b/src/shell/client_remove
--- a/src/shell/client_remove
+++ b/src/shell/client_remove
@@ -27,44 +27,45 @@
 # 需要 master_install 設定的參數區
 # Master IP here
 Master_IP_Address=your.master.ip.here
-# Master Hostname here
-Master_Hostname=input_your_master_hostname
-crawlzilla_PATH=/home/crawler/crawlzilla/system
+
+Crawlzilla_PATH=/home/crawler/crawlzilla/system
+
+Crawlzilla_HOME="/home/crawler/crawlzilla"
+Manu_Tmp_Path="/home/crawler/crawlzilla/.menu_tmp"
+Hadoop_Daemon="/opt/crawlzilla/nutch/bin/hadoop-daemon.sh"
+PID_Dir="/var/log/crawlzilla/hadoop-pids"
 
 
-[ "`id -u`" != "0" ] && echo "plaese enter password of $USER:"  && exec sudo su -c "$0" "$@"
+# [ System Load] #
+## language load 
+source $Manu_Tmp_Path/lang
 
-##########  echo function  ##########
-function debug_info () {
-  if [ $? -eq 0 ]; then
-    echo -e "\033[1;35;40m info - $1 \033[0m"
-  fi
+#  [ Function Description ] #
+
+function error_info ( )
+{ 
+    echo -e "\033[1;35;40m ERROR: $1 \033[0m" 
 }
-
-
-function show_info () {
-  if [ $? -eq 0 ]; then
+function show_info ( ) 
+{
     echo -e "\033[1;32;40m $1 \033[0m"
-  fi
 }
-##########end echo function ##########
-
-function load_default_lang(){
-
-lang=$(locale | grep 'LANG=' | cut -d "=" -f2)
-
-# Default: source english
-. $crawlzilla_PATH/lang/lang_en_US
-# if locale is zh then source chinese
-
-echo $lang | grep 'zh' >> /dev/null && source $crawlzilla_PATH/lang/lang_zh_TW
-}
-
-
 
 # check root
-function check_root(){
-  debug_info "check_root"
+function check_root ( )
+{
+  [ "`id -u`" != "0" ] && echo "plaese enter password of $USER:"  && exec sudo su -c "$0" "$@"
+  if [ $USER != "root" ]; then
+    show_info "$MR_check_root_1" # "請切換成 root 身份執行移除程式!!!"
+    exit
+  fi
+  show_info "$MR_check_root_2" # "已確認為root身份, 將繼續執行此移除程式！"
+}
+
+# check root
+function check_root ( )
+{
+  [ "`id -u`" != "0" ] && echo "plaese enter password of $USER:"  && exec sudo su -c "$0" "$@"
   if [ $USER != "root" ]; then
     show_info "$CR_check_root_1" # "請切換成 root 身份執行移除程式!!!"
     exit
@@ -77,24 +78,28 @@ function shutdown_service () {
   show_info "$CR_shutdown_service_echo_1" # "關閉本機服務..."
   su crawler -c "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop datanode"
   su crawler -c "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop tasktracker"
+  if [ -e $PID_Dir/hadoop-crawler-datanode.pid ] || \
+   [ -e $PID_Dir/hadoop-crawler-tasktracker.pid ] || ;then
+    kill -9 $(cat $PID_Dir/hadoop-crawler-datanode.pid) > /dev/null 2>&1 
+    if [ ! $? -eq 0 ];then echo "datanode error !";fi
+    kill -9 $(cat $PID_Dir/hadoop-crawler-tasktracker.pid) > /dev/null 2>&1
+    if [ ! $? -eq 0 ];then echo "tasktracker error !";fi
+  else 
+   echo "ERROR ! cannot find $PID_Dir/*pid file"
+   exit 8
+  fi
+
   show_info "$CR_shutdown_service_echo_2" # "本機服務已關閉"
 }
 
 # 移除檔案及資料夾
 function remove_folders () {
   show_info "$CR_remove_folders_echo_1" # "正在刪除安裝時所建立的檔案及資料夾..."
+  rm /usr/bin/crawlzilla
   rm /usr/bin/crawlzilla_remove
   rm -rf /opt/crawlzilla
-  rm -rf /var/lib/crawlzilla
-  rm -rf /var/log/crawlzilla/
- 
-## remove /tmp/xx => unnecessary
-#  fileList=$(ls -al /tmp | grep crawler | awk '{print $8}')
-#    for file in $(echo $fileList)
-#      do
-#        rm -rf /tmp/$file
-#    done
-  
+  rm -rf /var/log/crawlzilla
+  rm -rf /var/lib/crawlzilla 
   show_info "$CR_remove_folders_echo_2" # "安裝時所建立的檔案及資料夾已刪除"
 }
 
@@ -111,15 +116,16 @@ function edit_hosts () {
     cp /home/crawler/crawlzilla/system/hosts /etc/hosts
     show_info "still using the /etc/hosts created by crawlzilla "
   elif [ -f /etc/hosts ];then
-    show_info "/etc/hosts without recovered!!!"
+    show_info " WARNNING ! Please check your /etc/hosts correct or not!"
   else
-    show_info " bug ! /etc/hosts error !!!"
+    show_info " BUG ! /etc/hosts error !!!"
   fi
 }
 
-function edit_remove_list(){
+function edit_remove_list ( ) 
+{
 # 透過scp master上的檔案判斷是否有網路or master是否有開啟
-  scp -o StrictHostKeyChecking=no /etc/hosts crawler@$Master_IP_Address:/home/crawler/crawlzilla/system/go.sh /home/crawler/crawlzilla/system/ 
+ su crawler -c "scp -o StrictHostKeyChecking=no crawler@$Master_IP_Address:/home/crawler/crawlzilla/system/go.sh /home/crawler/crawlzilla/system/"
   if [ -e "/home/crawler/crawlzilla/system/go.sh" ] ;then
     Client_Hostname=$(hostname)
     IP_Address=$(cat /etc/hosts | grep $Client_Hostname | awk '{print $1}')
@@ -141,39 +147,47 @@ function user_delete () {
 
 # Main function
 function main () {
-  load_default_lang
-  check_root
   show_info "$CR_main_echo_1" #"警告 - 此一程式為移除此用戶端的crawl node, 若您為誤執行此一程式, 請按Ctrl+c離開此程序！"
   show_info "$CR_main_echo_2" #"本執行程序將會移除安裝crawlzilla時所新增的檔案及crawler使用者帳號"
-# 詢問是否繼續
-  read -p "$CR_main_echo_3" confirm # "請問是否確定移除此一節點：1.確定 2.取消"
-# 確認移除
-  if [ $confirm -eq 1 ]; then
-    shutdown_service
-    remove_folders
-    edit_remove_list
-    edit_hosts
-    user_delete
-    show_info "$CR_main_echo_4" # "移除程序已完成！"
-  elif [ $confirm -eq 2 ]; then
-    show_info "$CR_main_echo_5" # "您已取消移除程序！"
-    show_info "$CR_main_echo_6" # "若要移除請再重新執行！"
-  fi
-  
-  if [ $remove_flag -eq 1 ]; then
-    show_info "You need to edit /home/crawler/crawlzilla/system/crawl_nodes and hosts at host $Master_IP_Address due to you lost connect."
-  fi
+  # confirm 
+  LOCK=0
+  while [ "$LOCK" == "0" ];
+  do
+ 	# 詢問是否繼續
+	read -p "$CR_main_echo_3" confirm # "請問是否確定移除此一節點：1.確定 2.取消"
+	# 確認移除
+	if [ $confirm -eq 1 ]; then
+	  shutdown_service
+	  remove_folders
+	  edit_remove_list
+	  edit_hosts
+	  user_delete
+	  show_info "$CR_main_echo_4" # "移除程序已完成！"
+	  if [ $remove_flag -eq 1 ]; then
+	      show_info "You need to edit /home/crawler/crawlzilla/system/crawl_nodes "
+	      show_info "located at $Master_IP_Address manually because the connection is losted."
+	  fi
+          LOCK=1; 
+	elif [ $confirm -eq 2 ]; then
+	  show_info "$CR_main_echo_5" # "您已取消移除程序！"
+	  show_info "$CR_main_echo_6" # "若要移除請再重新執行！"
+          LOCK=1; 
+	else
+	  show_info "Hint: 1 => yes, 2 => exit "
+	  show_info "Please enter 1 or 2"
+	fi
+  done
 }
 
-if [ -e "/home/crawler/crawlzilla" ]; then
-  main
-else
+# [ Process Go ]
+check_root
+if [ ! -e "/home/crawler/crawlzilla" ] || [ ! -e "/opt/crawlzilla" ] ; then
   show_info "Installation is not complete!"
   show_info "Remove forcibly[1=agree/2=exit]"
   read -p "[1/2]: " force_do_remove
-  if [ $force_do_remove -eq 1 ];then
-    main
-  else
-    exit
+  if [ ! "$force_do_remove" == "1" ];then
+    exit 0;
   fi
 fi
+main
+
diff --git a/src/shell/master_remove b/src/shell/master_remove
--- a/src/shell/master_remove
+++ b/src/shell/master_remove
@@ -23,43 +23,35 @@
 #    1.0
 # History:
 #   
-[ "`id -u`" != "0" ] && echo "plaese enter password of $USER:"  && exec sudo su -c "$0" "$@"
 
-Work_Path=`dirname "$0"`
+# [ Env para ] #
+Crawlzilla_HOME="/home/crawler/crawlzilla"
+Manu_Tmp_Path="/home/crawler/crawlzilla/.menu_tmp"
+Hadoop_Daemon="/opt/crawlzilla/nutch/bin/hadoop-daemon.sh"
+PID_Dir="/var/log/crawlzilla/hadoop-pids"
 
-##########  echo function  ##########
-function debug_info () {
-  if [ $? -eq 0 ]; then
-    echo -e "\033[1;35;40m info - $1 \033[0m"
-  fi
+
+# [ System Load] #
+## check user
+#[ "`id -u`" != "0" ] && echo "please enter password of $USER:"  && exec sudo su -c "$0" "$@"
+## language load 
+source $Manu_Tmp_Path/lang
+
+#  [ Function Description ] #
+
+function error_info ( )
+{ 
+    echo -e "\033[1;35;40m ERROR: $1 \033[0m" 
 }
-
-
-function show_info () {
-  if [ $? -eq 0 ]; then
+function show_info ( ) 
+{
     echo -e "\033[1;32;40m $1 \033[0m"
-  fi
-}
-##########end echo function ##########
-
-crawlzilla_PATH=/home/crawler/crawlzilla/system
-
-
-function load_default_lang(){
-
-lang=$(locale | grep 'LANG=' | cut -d "=" -f2)
-
-# Default: source english
-. $crawlzilla_PATH/lang/lang_en_US
-# if locale is zh then source chinese
-
-echo $lang | grep 'zh' >> /dev/null && source $crawlzilla_PATH/lang/lang_zh_TW
-
 }
 
 # check root
-function check_root(){
-  debug_info "check_root"
+function check_root ( )
+{
+  [ "`id -u`" != "0" ] && echo "plaese enter password of $USER:"  && exec sudo su -c "$0" "$@"
   if [ $USER != "root" ]; then
     show_info "$MR_check_root_1" # "請切換成 root 身份執行移除程式!!!"
     exit
@@ -67,51 +59,50 @@ function check_root(){
   show_info "$MR_check_root_2" # "已確認為root身份, 將繼續執行此移除程式！"
 }
 
-# shutdown service
-function shutdown_service () {
-  show_info "$MR_shutdown_service_echo_1" # "停止其他尚未關閉的slaves服務..."
-  slaves_list=`cat /home/crawler/crawlzilla/system/crawl_nodes | cut -d' ' -f1`
-  for i in $slaves_list ;
-  do
-      show_info "$i $MR_shutdown_service_echo_2" # "關閉本機服務..."
-      su crawler -c 'ssh -o StrictHostKeyChecking=no crawler@$i "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop tasktracker"'
-      su crawler -c 'ssh -o StrictHostKeyChecking=no crawler@$i "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop datanode"'
-  done  
 
-  show_info "$i $MR_shutdown_service_echo_2" # "關閉本機服務..."
-  su crawler -c "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop jobtracker"
-  su crawler -c "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop namenode"
-
-
-
-  tom_pids=$(ps x | grep -v 'grep' | grep "tomcat" | awk '{print $1}')  
-  if [ -n "$tom_pids" ]; then
-    su crawler -c "/opt/crawlzilla/tomcat/bin/shutdown.sh"
+#function for fast_shutdown_all computing nodes and tomcat server
+function fast_shutdown_all ( )
+{
+  # shutdown tomcat
+    show_info "$tomcat_switch_echo_4"
+    tom_pids=$(ps ax | grep -v 'grep' | grep "tomcat" | awk '{print $1}')
+    for tom_pid in $tom_pids
+    do
+        kill -9 $tom_pid 2>/dev/null
+    done
+  # kill hadoop
+  if [ -e $PID_Dir/hadoop-crawler-datanode.pid ] || \
+   [ -e $PID_Dir/hadoop-crawler-tasktracker.pid ] || \
+   [ -e $PID_Dir/hadoop-crawler-namenodenode.pid ] || \
+   [ -e $PID_Dir/hadoop-crawler-jobtracke.pid ];then
+    kill -9 $(cat $PID_Dir/hadoop-crawler-datanode.pid) > /dev/null 2>&1 
+    if [ ! $? -eq 0 ];then echo "datanode error !";fi
+    kill -9 $(cat $PID_Dir/hadoop-crawler-tasktracker.pid) > /dev/null 2>&1
+    if [ ! $? -eq 0 ];then echo "tasktracker error !";fi
+    kill -9 $(cat $PID_Dir/hadoop-crawler-namenode.pid) > /dev/null 2>&1
+    if [ ! $? -eq 0 ];then echo "namenode error !";fi
+    kill -9 $(cat $PID_Dir/hadoop-crawler-jobtracker.pid) > /dev/null 2>&1
+    if [ ! $? -eq 0 ];then echo "jobtracker error !";fi
+  else 
+   echo "ERROR ! cannot find $PID_Dir/*pid file"
+   exit 8
   fi
-  show_info "$MR_shutdown_service_echo_3" # "本機服務已關閉"
 }
 
 # 移除檔案及資料夾
 function remove_folders () {
+  show_info "$MR_remove_folders_echo_1" # "正在刪除安裝時所建立的檔案及資料夾..."
   rm /usr/bin/crawlzilla
   rm /usr/bin/crawlzilla_remove
-  show_info "$MR_remove_folders_echo_1" # "正在刪除安裝時所建立的檔案及資料夾..."
   rm -rf /opt/crawlzilla
   rm -rf /var/log/crawlzilla
   rm -rf /var/lib/crawlzilla
-
-#  # remove /tmp/xx => unnecessary
-#  fileList=$(ls -al /tmp | grep crawler | awk '{print $8}')
-#  for file in $(echo $fileList)
-#    do
-#      rm -rf /tmp/$file
-#    done
   
   show_info "$MR_remove_folders_echo_2" # "安裝時所建立的檔案及資料夾已刪除"
 }
 
-# 還原/etc/hosts
-function edit_hosts () {
+# recover /etc/hosts
+function recover_hosts () {
   show_info "$CR_edit_hosts_echo_1" # "修改/etc/hosts..."
   if [ -e /home/crawler/crawlzilla/system/hosts.bak ];then
     rm /etc/hosts
@@ -122,13 +113,13 @@ function edit_hosts () {
     cp /home/crawler/crawlzilla/system/hosts /etc/hosts
     show_info "still using the /etc/hosts created by crawlzilla. "
   elif [ -f /etc/hosts ];then
-    show_info "/etc/hosts without recovered!!!"
+    show_info " WARNNING ! Please check your /etc/hosts correct or not!"
   else
-    show_info " bug ! /etc/hosts error !!!"
+    show_info " BUG ! /etc/hosts error !!!"
   fi
 }
 
-# 移除使用者
+# remove user
 function user_delete () {
   show_info "$MR_user_delete_echo_1" # "正在刪除crawler使用者..."
   userdel -rf crawler >/dev/null 2>&1
@@ -138,34 +129,45 @@ function user_delete () {
 
 # Main function
 function main () {
-  load_default_lang
-  check_root
-  show_info "$MR_main_echo_1" #"警告 - 此一程式為移除Crawlzilla程式, 若您為誤執行此一程式, 請按Ctrl+c離開此程序！"
-  show_info "$MR_main_echo_2" #"本執行程序將會移除安裝Crawlzilla時所新增的檔案及crawler使用者帳號"
-# 詢問是否繼續
-  read -p "$MR_main_echo_3" confirm # "請問是否確定移除此一節點：1.確定 2.取消"
-# 確認移除
-  if [ $confirm -eq 1 ]; then
-    shutdown_service
-    remove_folders
-    edit_hosts
-    user_delete
-    show_info "$MR_main_echo_4" # "移除程序已完成！"
-  elif [ $confirm -eq 2 ]; then
-    show_info "$MR_main_echo_5" # "您已取消移除程序！"
-    show_info "$MR_main_echo_6" # "若要移除請再重新執行！"
-  fi
+  show_info "$MR_main_echo_1" # a warnning hint
+  show_info "$MR_main_echo_2" # a remove hint 
+  # confirm 
+  LOCK=0
+  while [ "$LOCK" == "0" ];
+  do
+    read -p "$MR_main_echo_3" confirm # confirm 1.確定 2.取消"
+  # make sure
+    if [ $confirm -eq 1 ]; then
+      fast_shutdown_all
+      show_info "shutdown service"
+      remove_folders
+      show_info "remove_folders"
+      recover_hosts
+      show_info "recover hosts"
+      user_delete
+      show_info "user_delete"
+      show_info "$MR_main_echo_4" # "移除程序已完成！"
+      LOCK=1; 
+    elif [ $confirm -eq 2 ]; then
+      show_info "$MR_main_echo_5" # "您已取消移除程序！"
+      show_info "$MR_main_echo_6" # "若要移除請再重新執行！"
+      LOCK=1; 
+    else
+      show_info "Hint: 1 => yes, 2 => exit "
+      show_info "Please enter 1 or 2"
+    fi
+  done
 }
 
-if [ -e "/home/crawler/crawlzilla" ]; then
-  main
-else
+# [ Process Go ]
+
+check_root
+if [ ! -e "/home/crawler/crawlzilla" ] || [ ! -e "/opt/crawlzilla" ] ; then
   show_info "Installation is not complete!"
   show_info "Remove forcibly[1=agree/2=exit]"
   read -p "[1/2]: " force_do_remove
-  if [ $force_do_remove -eq 1 ];then
-    main
-  else 
-    exit
+  if [ ! "$force_do_remove" == "1" ];then
+    exit 0;
   fi
 fi
+main
