fix : change jps to ps
M    src/shell/crawlzilla

diff --git a/src/shell/crawlzilla b/src/shell/crawlzilla
--- a/src/shell/crawlzilla
+++ b/src/shell/crawlzilla
@@ -40,6 +40,7 @@ PID_Dir="/var/log/crawlzilla/hadoop-pids"
 source "/home/crawler/crawlzilla/system/log.sh" main_menu;
 
 # [Env Declaration] #
+PID="0"
 ## menu choise menu_tmp dir check
 if [ ! -d $Manu_Tmp_Path ];then 
    mkdir $Manu_Tmp_Path;
@@ -50,7 +51,15 @@ fi
 
 function CheckPID ( )
 {
-  ssh -o StrictHostKeyChecking=no $1 "ps $2 |grep $2 > /dev/null 2>&1"
+  # $1 is ip , $2 is job
+  local PID_cat="cat $PID_Dir/hadoop-crawler-$2.pid"
+  if [ "$1" == "localhost" ];then 
+    PID=$($PID_cat)
+    ps $PID |grep $PID > /dev/null 2>&1
+  else
+    PID=$(ssh -o StrictHostKeyChecking=no $1 "cat $PID_Dir/hadoop-crawler-$2.pid")
+    ssh -o StrictHostKeyChecking=no $1 "ps $PID |grep $PID > /dev/null 2>&1"
+  fi
   return $?
 }
 
@@ -61,27 +70,30 @@ if [ ! "$USER" == "crawler" ];then show_info "Error! You are $USER, please chang
 local NODE=$1
 local JOB=$2
 local Daemon_Start="$Hadoop_Daemon start $JOB"
+local sh_do
 declare -i LOCK=0
 while [ $LOCK -lt 3 ]
 do
-local PID=$(ssh -o StrictHostKeyChecking=no $NODE "cat $PID_Dir/hadoop-crawler-$JOB.pid")
-  if CheckPID $NODE $PID; then
+  if CheckPID $NODE $JOB; then
     debug_info "    *** $JOB ($PID) is working "
     declare -i LOCK=9
   else
     declare -i LOCK=LOCK+1
-    show_info "    *** $JOB not work, starting now ... $LOCK *** ";
-    debug_info "ssh -o StrictHostKeyChecking=no $NODE $Daemon_Start 2>/dev/null"
-    ssh -o StrictHostKeyChecking=no $NODE "$Daemon_Start >/dev/null  2>&1"
+    show_info "    *** $NODE 's $JOB not work, starting now ... $LOCK *** ";
+    # if service is local such as namenode, skip using ssh
+    if [ "$NODE" == "localhost" ];then
+      $($Daemon_Start >/dev/null  2>&1)
+    else 
+      ssh -o StrictHostKeyChecking=no $NODE "$Daemon_Start >/dev/null  2>&1"
+    fi
     sleep 1
   fi
 done
 
 if [ $LOCK -eq 3 ];then
-  local hostname=$(hostname)
-  show_info "ERROR! $JOB starting failed, please check /var/log/crawlzilla/hadoop-logs/hadoop-crawler-$JOB-$hostname.log"; exit 1;
+  show_info "ERROR! $NODE 's $JOB starting failed, please check /var/log/crawlzilla/hadoop-logs/hadoop-crawler-$JOB-*.log"; exit 1;
 elif [ $LOCK -eq 9 ];then
-  show_info "$JOB status .... [RUNNING]"
+  show_info "| $NODE | $JOB status .... [RUNNING]"
 else
   show_info "BUG!! Crawlzilla System Error Bug."; exit 1;
 fi
@@ -98,12 +110,19 @@ declare -i LOCK=0
 while [ $LOCK -lt 3 ]
 do
   PID=$(ssh -o StrictHostKeyChecking=no $NODE "cat $PID_Dir/hadoop-crawler-$JOB.pid")
-  if CheckPID $NODE $PID; then
+  if CheckPID $NODE $JOB; then
     # job is work, stop it
     declare -i LOCK=LOCK+1
-    show_info "   *** $JOB ($PID) is working , stoping now ... $LOCK *** ";
+    show_info "   *** $NODE 's $JOB ($PID) is working , stoping now ... $LOCK *** ";
     debug_info "ssh -o StrictHostKeyChecking=no $NODE $Daemon_Stop 2>/dev/null"
-    ssh -o StrictHostKeyChecking=no $NODE "$Daemon_Stop >/dev/null  2>&1"
+
+    # if service is local such as namenode, skip using ssh
+    if [ "$NODE" == "localhost" ];then
+      $($Daemon_Stop >/dev/null  2>&1)
+    else
+	ssh -o StrictHostKeyChecking=no $NODE "$Daemon_Stop >/dev/null  2>&1" 
+    fi 
+
     sleep 3
   else
     # job is not work , ok, down work
@@ -113,16 +132,15 @@ do
 done
 
 if [ $LOCK -eq 3 ];then
-  local hostname=$(hostname)
   ssh -o StrictHostKeyChecking=no $NODE "kill -9 $PID 2>/dev/null"
   if [ "$?" == "0" ]; then
-    show_info "$JOB ($PID) is killed, status .... [Stopped] "
+    show_info " $NODE 's $JOB ($PID) is killed, status .... [Stopped] "
   else 
-    show_info "Error! Stop $JOB failed"; exit 1;
+    show_info "Error! Stop  $NODE 's $JOB failed"; exit 1;
   fi 
-  show_info "please check /var/log/crawlzilla/hadoop-logs/hadoop-crawler-$JOB-$hostname.log"
+  show_info "please check $NODE 's /var/log/crawlzilla/hadoop-logs/hadoop-crawler-$JOB-*.log"
 elif [ $LOCK -eq 9 ];then
-  show_info "$JOB status .... [Stopped]"
+  show_info "| $NODE | $JOB status .... [Stopped]"
 else
   show_info "BUG!! Crawlzilla System Error Bug."; exit 1;
 fi
@@ -234,7 +252,7 @@ $DIALOG --clear --backtitle "$dia_back" \
         "cluster_status" "$dia_main_menu_1_1" \
         "fast_manage"  "$dia_main_menu_1_2" \
         "cluster_setup" "$dia_main_menu_1_3" \
-        "server_setup" "$dia_main_menu_1_4" \
+        "master_setup" "$dia_main_menu_1_4" \
         "tomcat_switch" "$dia_main_menu_1_5" \
         "tomcat_port" "$dia_main_menu_1_6" \
         "lang_switch" "$dia_main_menu_1_7" \
@@ -247,8 +265,7 @@ function cluster_status(){
 IP_list=$(cat $Crawlzilla_HOME/system/crawl_nodes | grep -v '^$' | grep -v '#'  | awk '{print $1}')
 clusterStatus="$Manu_Tmp_Path/clusterStatus"
 rm $clusterStatus 2> /dev/null
-#printf '%16s\t %11s\t %10s\t %25s\n' "[IP] [Hostanme] [Network] [Datanode & Tasktracker]" >>$clusterStatus
-echo -e "$cluster_status_echo_1" >>$clusterStatus
+echo -e "$cluster_status_echo_1" >>$clusterStatus   # main bar [IP] [Hostname]...
 echo -e "------------------------------------------------------------------------" >>$clusterStatus
 echo -e "\n$cluster_status_echo_2"
 for ip in $IP_list
@@ -259,13 +276,30 @@ do
     # Check Hadoop/Nutch service through ssh
     Task_Data_status="shutdown"
     if [ $ip_status == "online" ]; then
-    Task_Data=$(ssh -o StrictHostKeyChecking=no $ip "jps |grep TaskTracker ; jps | grep  DataNode")
-    [ -z "$Task_Data" ] || Task_Data_status="running"
+      # Check datanode or tasktracker run or not
+      DataNode_status="down"
+      TaskTracker_status="down"
+      # CheckPID <ipaddr> <job> => receive 0 , job is running;
+      if CheckPID $ip datanode ;then DataNode_status="ok"; fi
+      if CheckPID $ip tasktracker ;then TaskTracker_status="ok"; fi
+      if [ "$DataNode_status" == "ok" ];then
+	if [ "$TaskTracker_status" == "ok" ];then
+	  Task_Data_status="Run"
+	else
+	  Task_Data_status="Warn(T)"
+	fi
+      else
+	if [ "$TaskTracker_status" == "ok" ];then
+	  Task_Data_status="Warn(D)"
+	else
+	  Task_Data_status="Down"
+	fi
+      fi
+
     fi
 
     host_name=$(cat $Crawlzilla_HOME/system/crawl_nodes | grep $ip | awk '{print $2}')
     echo -e "$ip  $host_name \t\t $ip_status \t $Task_Data_status" >>$clusterStatus
-#    printf '%16s\t %11s\t %10s\t %25s\n' "$ip $host_name $ip_status $Task_Data_status" >>$clusterStatus
 done
 
 #read -p "$cluster_status_read_1"
@@ -307,23 +341,34 @@ function fast_manage(){
 
 
 ## [Server Setup (namenode & jobtracker)] ##
-function server_setup(){
+function master_setup ( )
+{
 serverSetup=$Manu_Tmp_Path/serverSetup
-pid_name=$(jps | grep NameNode)
-pid_job=$(jps | grep JobTracker)
 
-if [ -z "$pid_name" -a -z "$pid_job" ]; then                                                                                               
-    $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_1" \
-    --msgbox "$dia_server_msg_1" 7 50
-elif [ -z "$pid_name" -a -n "$pid_job" ]; then
-    $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_1" \
-    --msgbox "$dia_server_msg_2" 7 50
-elif [ -n "$pid_name" -a -z "$pid_job" ]; then
-    $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_1" \
-    --msgbox "$dia_server_msg_3" 7 50
-else
+if CheckPID localhost namenode ;then N_status="ok"; fi
+if CheckPID localhost jobtracker ;then J_status="ok"; fi
+
+if [ "$N_status" == "ok" ];then
+  if [ "$N_status" == "ok" ];then
+    ## N & J run
     $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_1" \
     --msgbox "$dia_server_msg_4" 7 50
+  else 
+    ## N run , but J not
+    $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_1" \
+    --msgbox "$dia_server_msg_3" 7 50
+  fi
+else 
+  if [ "$N_status" == "ok" ];then
+    ## J run , but N not
+    $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_1" \
+    --msgbox "$dia_server_msg_2" 7 50
+  else 
+    ## N & J down
+    $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_1" \
+    --msgbox "$dia_server_msg_1" 7 50
+
+  fi
 fi
 
 $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_2" \
@@ -334,26 +379,29 @@ $DIALOG --clear --backtitle "$dia_back" --title "$dia_server_title_2" \
     "main" "$dia_backto_main" 2>$serverSetup
 
 if [ "$(cat $serverSetup)" == "start" ]; then
-    HadoopStart $(hostname) namenode
-    HadoopStart $(hostname) jobtracker
+   #  ori
+   #    HadoopStart $(hostname) namenode
+   #    HadoopStart $(hostname) namenode
+    HadoopStart localhost namenode
+    HadoopStart localhost jobtracker
     # Back to main menu
     read -p "Press Enter to continue.. "
     main_menu
     menu_choose
 elif [ "$(cat $serverSetup)" == "shutdown" ]; then
-    HadoopStop $(hostname) jobtracker
-    HadoopStop $(hostname) namenode
+    HadoopStop localhost jobtracker
+    HadoopStop localhost namenode
     # Back to main menu
     read -p "Press Enter to continue.. "
     main_menu
     menu_choose
 elif [ "$(cat $serverSetup)" == "restart" ]; then
-    HadoopStop $(hostname) jobtracker
-    HadoopStop $(hostname) namenode
+    HadoopStop localhost jobtracker
+    HadoopStop localhost namenode
     sleep 3
-    HadoopStart $(hostname) namenode
+    HadoopStart localhost namenode
     sleep 3
-    HadoopStart $(hostname) jobtracker
+    HadoopStart localhost jobtracker
     # Back to main menu
     read -p "Press Enter to continue.. "
     main_menu
@@ -491,14 +539,12 @@ fi
 
 # jude $Tomcat_HOME/bin/startup.sh 
 if [ ! -e $Tomcat_HOME/bin/startup.sh ]; then
-    # echo -e "\n$tomcat_switch_echo_1 $Tomcat_HOME/bin/startup.sh"
     show_info "\n$tomcat_switch_echo_1 $Tomcat_HOME/bin/startup.sh"
     exit
 fi
 
 if [ ! -e $Tomcat_HOME/bin/shutdown.sh ]; then
     show_info "\n$tomcat_switch_echo_1 $Tomcat_HOME/bin/shutdown.sh"
-    #echo -e "\n$tomcat_switch_echo_1 $Tomcat_HOME/bin/shutdown.sh"
     exit
 fi
 
@@ -596,71 +642,34 @@ function fast_startup_all(){
   show_info "$tomcat_switch_echo_3"
 
   # startup namenode and jobtracker
-  HadoopStart $(hostname) namenode
+  HadoopStart localhost namenode
   sleep 3
-  HadoopStart $(hostname) jobtracker
+  HadoopStart localhost jobtracker
 
   # startup datanode and tasktracker
   IP_list=$(cat $Crawlzilla_HOME/system/crawl_nodes | grep -v '^$' | grep -v '#'  | awk '{print $1}')
   for ip in $IP_list
     do
-      # Check Network status
-#      ip_status="online"
-#      ping -c1 -w1 $ip 2>&1 > /dev/null || ip_status="offline"
-      # Check Hadoop/Nutch service through ssh
-#      Task_Data_status="shutdown"
-
-    HadoopStart $ip datanode
-    HadoopStart $ip tasktracker
-
-#      if [ $ip_status == "online" ]; then
-#        Task_Data=$(ssh -o StrictHostKeyChecking=no $ip "jps |grep TaskTracker ; jps | grep  DataNode")
-#      fi
-#
-#      if [ -z"$Task_Data" ] ;then
-#        ssh -o StrictHostKeyChecking=no $node "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh start datanode \
-#        ; /opt/crawlzilla/nutch/bin/hadoop-daemon.sh start tasktracker" 2>/dev/null
-#      fi
+      HadoopStart $ip datanode
+      HadoopStart $ip tasktracker
     done
 }
 
 #function for fast_shutdown_all computing nodes and tomcat server
 function fast_shutdown_all(){
   # shutdown tomcat
-    Tomcat_Shutdown 
-#  pid_name=$(jps | grep NameNode)
-#  pid_job=$(jps | grep JobTracker)
-#  if [ -n "$pid_name" ]; then
-#    /opt/crawlzilla/nutch/bin/stop-dfs.sh
-#  fi
-#  if [ -n "$pid_job" ]; then
-#    /opt/crawlzilla/nutch/bin/stop-mapred.sh
-#  fi
+  Tomcat_Shutdown 
   IP_list=$(cat $Crawlzilla_HOME/system/crawl_nodes | grep -v '^$' | grep -v '#'  | awk '{print $1}')
   # shutdown datanode and tasktracker
   for ip in $IP_list
     do
-
-    HadoopStop $ip datanode
-    HadoopStop $ip tasktracker
-
-#      # Check Network status
-#      ip_status="online"
-#      ping -c1 -w1 $ip 2>&1 > /dev/null || ip_status="offline"
-#      # Check Hadoop/Nutch service through ssh
-#      Task_Data_status="shutdown"
-#      if [ $ip_status == "online" ]; then
-#        Task_Data=$(ssh -o StrictHostKeyChecking=no $ip "jps |grep TaskTracker ; jps | grep  DataNode")
-#      fi    
-#      if [ -n "$Task_Data" ] ;then
-#        ssh -o StrictHostKeyChecking=no $node "/opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop datanode \
-#        ; /opt/crawlzilla/nutch/bin/hadoop-daemon.sh stop tasktracker" 2>/dev/null
-#      fi
+      HadoopStop $ip datanode
+      HadoopStop $ip tasktracker
     done
 
   # shutdown namenode and jobtracker
-  HadoopStop $(hostname) jobtracker
-  HadoopStop $(hostname) namenode
+  HadoopStop localhost jobtracker
+  HadoopStop localhost namenode
   sleep 3
 }
 
@@ -673,8 +682,8 @@ case $(cat $main_choice) in
         cluster_setup;;
     "fast_manage")
         fast_manage;;
-    "server_setup")    
-        server_setup;;
+    "master_setup")    
+        master_setup;;
     "tomcat_switch")
         tomcat_switch;;
     "tomcat_port")
